import os
import PySpice.Logging.Logging as Logging
from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *
from PySpice.Spice.Library import SpiceLibrary

# Configure Logging for Simulation
logger = Logging.setup_logging()

class PySpiceTool:
    """
    Electronic Simulation Engine for AI Agents.
    Converts logical circuits into SPICE models to run Transient and AC analyses.
    """

    def __init__(self, title: str = "AI_PCB_Simulation"):
        self.circuit = Circuit(title)
        # Path to standard SPICE models (Diodes, Transistors, etc.)
        self.libraries_path = "design/lib/spice_models"
        if os.path.exists(self.libraries_path):
            self.spice_library = SpiceLibrary(self.libraries_path)

    def run_transient_analysis(self, step_time: float = 1e-6, end_time: float = 10e-3):
        """
        Performs a Transient Analysis (Time Domain).
        Useful for checking power-on behavior and signal transitions.
        """
        try:
            simulator = self.circuit.simulator(temperature=25, nominal_temperature=25)
            analysis = simulator.transient(step_time=step_time @ u_s, end_time=end_time @ u_ms)
            return {"success": True, "analysis": analysis}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def check_voltage_rail(self, node_name: str, expected_v: float, tolerance: float = 0.05):
        """
        Utility for the PI (Power Integrity) Agent.
        Checks if a specific voltage rail stays within a percentage of its target.
        """
        # Note: Simulation must be run before calling this
        pass # Implementation depends on analysis results

    def add_power_source(self, dc_voltage: float, node_in: str = "V_IN", node_out: str = "0"):
        """Adds a DC Voltage source to the simulation."""
        self.circuit.V('input', node_in, node_out, dc_voltage @ u_V)

    def add_resistor(self, name: str, node1: str, node2: str, value_ohms: float):
        self.circuit.R(name, node1, node2, value_ohms @ u_Ohm)

    def add_capacitor(self, name: str, node1: str, node2: str, value_farads: float):
        self.circuit.C(name, node1, node2, value_farads @ u_F)

    def generate_spice_netlist(self):
        """Returns the raw SPICE code generated by the tool."""
        return str(self.circuit)

# Global Helper for SI/PI Agents
def simulate_power_integrity(v_in: float, load_resistance: float, decoupling_cap: float):
    """
    A quick test bench to see if a decoupling capacitor handles a load.
    Used by agents to verify component selection for power rails.
    """
    tool = PySpiceTool("PI_Verification")
    tool.add_power_source(v_in)
    tool.add_resistor('Load', 'V_IN', '0', load_resistance)
    tool.add_capacitor('Decouple', 'V_IN', '0', decoupling_cap)
    
    result = tool.run_transient_analysis()
    return result
  
