import json
import os
from typing import Dict, List, Any

class ArchitectureAgent:
    """
    The Planning Cluster: Architecture Agent.
    Consumes the Design Spec and creates a functional block diagram 
    and hardware architecture plan.
    """

    def __init__(self, spec_path: str = "design/config/active_spec.json"):
        self.spec_path = spec_path
        self.architecture = {
            "power_tree": [],
            "bus_mapping": {},
            "component_selection": [],
            "layer_recommendation": 2
        }

    def _load_spec(self) -> Dict[str, Any]:
        """Loads the JSON spec generated by the Requirements Agent."""
        if not os.path.exists(self.spec_path):
            # Fallback to defaults if spec doesn't exist
            return {"power": {"input_v": 5.0, "logic_v": 3.3}, "interfaces": ["I2C"]}
        with open(self.spec_path, 'r') as f:
            return json.load(f)

    def design_power_tree(self, spec: Dict[str, Any]):
        """
        Determines the regulation strategy.
        Example: If Input > 7V, use a Buck Converter. If < 7V, use an LDO.
        """
        input_v = spec["power"]["input_v"]
        logic_v = spec["power"]["logic_v"]

        # Stage 1: Primary Input
        self.architecture["power_tree"].append({
            "stage": "Input",
            "voltage": input_v,
            "net_name": "V_IN"
        })

        # Stage 2: Regulation
        if input_v > 7.0:
            reg_type = "Buck Converter"
            part_alias = "buck_mp2315" # High-efficiency choice
        else:
            reg_type = "LDO"
            part_alias = "ams1117_3v3" # Standard choice

        self.architecture["power_tree"].append({
            "stage": "Regulation",
            "type": reg_type,
            "input": input_v,
            "output": logic_v,
            "part_alias": part_alias,
            "net_name": "+3.3V"
        })

    def map_buses(self, spec: Dict[str, Any]):
        """
        Assigns logical interfaces to specific MCU peripheral blocks.
        """
        mcu_family = spec.get("mcu", {}).get("family", "ESP32")
        
        # Logic for ESP32 Standard Pinout
        if mcu_family == "ESP32":
            if "I2C" in spec["interfaces"]:
                self.architecture["bus_mapping"]["I2C"] = {"SDA": "GPIO21", "SCL": "GPIO22"}
            if "UART" in spec["interfaces"]:
                self.architecture["bus_mapping"]["UART"] = {"TX": "GPIO1", "RX": "GPIO3"}

    def run(self):
        """Executes the architecture planning phase."""
        print("📐 ArchAgent: Generating hardware architecture...")
        spec = self._load_spec()
        
        self.design_power_tree(spec)
        self.map_buses(spec)
        
        # Decide stackup complexity
        if len(spec.get("interfaces", [])) > 4:
            self.architecture["layer_recommendation"] = 4
        
        return self.architecture

    def save_architecture(self, filename="design/config/architecture_plan.json"):
        """Saves the plan for the Implementation Cluster (SKiDL Agent)."""
        with open(filename, 'w') as f:
            json.dump(self.architecture, f, indent=4)
        print(f"💾 ArchAgent: Architecture plan saved to {filename}")

if __name__ == "__main__":
    arch_agent = ArchitectureAgent()
    plan = arch_agent.run()
    print(json.dumps(plan, indent=2))
  
